name: close release candidate

on:
  issues:
    types:
      - closed

jobs:
  close_release_candidate:
    if: contains(github.event.issue.labels.*.name, 'release candidate')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: delete branch
        run: git push origin :release-candidate
