name: publish release

on:
  issues:
    types:
      - labeled

jobs:
  publish_release:
    if: github.event.issue.state == 'open' && contains(github.event.issue.labels.*.name, 'release candidate') && github.event.label.name == 'approve release'
    runs-on: ubuntu-latest
    env:
      CHANGELOG_PATH: /tmp/CHANGELOG.md
      IS_PRERELEASE: ${{ contains(github.event.issue.labels.*.name, 'prerelease') }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          ref: release-candidate
          fetch-depth: 0
      - uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # v2.5.2
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"
      - name: git config
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - run: yarn install --frozen-lockfile
      - run: yarn release
        if: ${{ env.IS_PRERELEASE == 'false' }}
      - run: yarn release --prerelease
        if: ${{ env.IS_PRERELEASE == 'true' }}
      - run: npm publish
        if: ${{ env.IS_PRERELEASE == 'false' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --tag prerelease
        if: ${{ env.IS_PRERELEASE == 'true' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: echo NEW_TAG=$(git describe) >> $GITHUB_ENV
      - run: git push origin $NEW_TAG
      - run: npx ts-node ./scripts/getLatestChangelog.ts > ${{ env.CHANGELOG_PATH }}
      - name: create release on GitHub
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          body_path: ${{ env.CHANGELOG_PATH }}
          commitish: main
          prerelease: ${{ env.IS_PRERELEASE }}
      - name: close issue
        uses: peter-evans/close-issue@a700eac5bf2a1c7a8cb6da0c13f93ed96fd53dbe # v1.0.3
      - name: delete branch
        run: git push origin :release-candidate
      - name: cherry-pick release commit
        run: |
          git checkout main
          git cherry-pick $NEW_TAG
      - name: craete pull request
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          title: "chore(release): ${{ env.NEW_TAG }}"
          branch: "merge-release-${{ env.NEW_TAG }}"
